/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package containsWebApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {

    @Test void test_foundOnSubArray() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
        assertTrue(App.searchOnSubArray(array, 2, 3, 2));
    }

    @Test void test_notFoundOnSubArray() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5, 6, 7));
        assertFalse(App.searchOnSubArray(array, 1, 4, 7));
    }

    @Test void test_emptyArray() {
        ArrayList<Integer> array = new ArrayList<>();
        assertFalse(App.searchOnSubArray(array, 1, 5, 2));
    }

    @Test void test_nullArray() {
        assertFalse(App.searchOnSubArray(null, 1, 5, 2));
    }

    @Test void test_falseIndexForSubArray() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5, 6, 7));
        assertFalse(App.searchOnSubArray(array, 0, 5, 2)); 

        assertFalse(App.searchOnSubArray(array, 1, 8, 2));
    }


}
